DROP TABLE people IF EXISTS;
DROP table livre IF EXISTS;

CREATE TABLE people  (
    person_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20)
);

CREATE TABLE livre (
  ean VARCHAR(250) IDENTITY NOT NULL PRIMARY KEY,
  titre VARCHAR(250)
);

